apiVersion: v1
kind: Secret
metadata:
  name: smtp
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    microservice: backend
    component: api-server
  annotations:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
stringData:
  SMTP_FROM_ADDRESS: {{ quote .Values.backend.smtp.fromAddress }}
  SMTP_PASSWORD: {{ quote .Values.backend.smtp.password }}
  SMTP_SERVER: {{ quote .Values.backend.smtp.server }}
  SMTP_PORT: {{ quote .Values.backend.smtp.port }}
  SMTP_USE_STARTTLS: {{ quote .Values.backend.smtp.tls }}
