apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    microservice: backend
    component: api-server
  annotations:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: {{ .Release.Name }}
      microservice: backend
      component: api-server
 
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        microservice: backend
        component: api-server

    spec:  # type: V1PodSpec
      containers:
      - name: backend
        
        image: yeldir/st3k101-backend
        imagePullPolicy: Always

        stdin: true
        tty: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

        env:
        - name: LANGUAGE
          value: {{ quote .Values.backend.locale.language }}
        - name: TIMEZONE
          value: {{ quote .Values.backend.locale.timezone }}
        - name: DOMAIN_NAME
          value: {{ list "https://" .Values.host | join "" }}
        - name: ADMIN_EMAIL
          value: {{ quote .Values.backend.monitoring.emailAddress }}
        - name: XAPI_DEFAULT_ENDPOINT
          value: {{ quote .Values.backend.xapi.defaultEndpoint }}

        - name: TLA_XAPI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: tla
              key: TLA_XAPI_ENDPOINT
        - name: TLA_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: tla
              key: TLA_AUTH_USERNAME
        - name: TLA_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tla
              key: TLA_AUTH_PASSWORD

        - name: SMTP_FROM_ADDRESS
          valueFrom:
            secretKeyRef:
              name: smtp
              key: SMTP_FROM_ADDRESS
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp
              key: SMTP_PASSWORD
        - name: SMTP_SERVER
          valueFrom:
            secretKeyRef:
              name: smtp
              key: SMTP_SERVER
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: smtp
              key: SMTP_PORT
        - name: SMTP_USE_STARTTLS
          valueFrom:
            secretKeyRef:
              name: smtp
              key: SMTP_USE_STARTTLS

        - name: DEBUG
          value: {{ quote .Values.backend.debug.enabled }}
        - name: DEBUG_SPOOF_LOCATION
          value: {{ quote .Values.backend.debug.spoofLocation }}

        - name: AUTH_SESSION_TOKEN_LENGTH
          value: "64"
        - name: AUTH_SALT_LENGTH
          value: "64"
        - name: AUTH_REQUEST_TTL
          value: "1800"
        - name: VERIFICATION_HASH_LENGTH
          value: "16"

        - name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: database
              key: SQLALCHEMY_DATABASE_URI
        
        - name: SURVEY_TEMPLATE_PATH
          value: "/app/templates/questionnaire"
        - name: XAPI_LOST_LOG
          value: {{ quote .Values.backend.xapi.lostLog }}
        - name: XAPI_MAX_RETRIES
          value: {{ quote .Values.backend.xapi.maxRetries }}

      initContainers:
      - name: init-wait-until-postgres-available
        image: busybox
        command: ["sh", "-c", "until nslookup postgres; do echo 'waiting for Service postgres'; sleep 2; done;"]

      - name: init-wait-unil-postgres-accepts
        image: busybox
        command: ["sh", "-c", "until nc -z postgres 5432; do echo 'waiting for postgres to accept connection'; sleep 2; done;"]

      dnsPolicy: ClusterFirst

      restartPolicy: Always
      terminationGracePeriodSeconds: 30