apiVersion: apps/v1
kind: Deployment
metadata:
  name: xapi-publisher
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    microservice: xapi-publisher
    component: api-server
  annotations:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: {{ .Release.Name }}
      microservice: xapi-publisher
      component: api-server
 
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        microservice: xapi-publisher
        component: api-server

    spec:  # type: V1PodSpec
      containers:
      - name: xapi-publisher
        
        image: yeldir/st3k101-xapi-publisher
        imagePullPolicy: Always

        stdin: true
        tty: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

      dnsPolicy: ClusterFirst

      restartPolicy: always
      terminationGracePeriodSeconds: 30