apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    microservice: backend
    component: message-broker
  annotations:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.xapiPublisher.messageBroker.size }}
  storageClassName: {{ .Values.xapiPublisher.messageBroker.storageClassName }}
