apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    microservice: xapi-publisher
    component: message-broker
  annotations:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: {{ .Release.Name }}
      microservice: xapi-publisher
      component: message-broker
 
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        microservice: xapi-publisher
        component: message-broker

    spec:  # type: V1PodSpec
      containers:
      - name: redis
        
        image: "redis:{{ .Values.xapi-publisher.message-broker.version }}"
        imagePullPolicy: Always

        stdin: true
        tty: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

        volumeMounts:
        - mountPath: /data
          name: redis-data

      dnsPolicy: ClusterFirst

      restartPolicy: always
      terminationGracePeriodSeconds: 60

      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
