apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    microservice: backend
    component: session-cache
  annotations:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: {{ .Release.Name }}
      microservice: backend
      component: session-cache
 
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        microservice: backend
        component: session-cache

    spec:  # type: V1PodSpec
      containers:
      - name: postgres
        
        image: memcached:1.5-alpine
        imagePullPolicy: Always

        stdin: true
        tty: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

      dnsPolicy: ClusterFirst

      restartPolicy: always
      terminationGracePeriodSeconds: 30
