apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    microservice: backend
    component: database
  annotations:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.backend.database.size }}
  storageClassName: {{ .Values.backend.database.storageClassName }}
