apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    microservice: backend
    component: database
  annotations:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.backend.database.user }}
  POSTGRES_PASSWORD: {{ .Values.backend.database.password }}