apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    microservice: xapi-publisher
    component: database
  annotations:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.xapi-publisher.database.size }}
  storageClassName: {{ .Values.xapi-publisher.database.storageClassName }}
